insert into players (realname, gamertag, email) values ("Josh", "JDawg", "c00270917@setu.ie");
insert into players (realname, gamertag, email) values ("Shane", "idk", "c00270031@setu.ie");
insert into players (realname, gamertag, email) values ("Alwyn", "alwyn", "c00271145@setu.ie");
insert into players (realname, gamertag, email) values ("Darragh", "FrogGranna", "c00271651@setu.ie");
insert into players (realname, gamertag, email) values ("Pavol", "PDawg", "c00272003@setu.ie");
insert into players (realname, gamertag, email) values ("Daniel", "frodo", "c00272187@setu.ie");
insert into players (realname, gamertag, email) values ("Richie", "The Legend 27", "c00272345@setu.ie");
insert into players (realname, gamertag, email) values ("Conor", "xxx_CDawg_xxx", "c00272506@setu.ie");
insert into players (realname, gamertag, email) values ("Jack", "Xx_TTV_MadJack69_xX", "c00273123@setu.ie");
insert into players (realname, gamertag, email) values ("Ruslan", "Ruark", "c00273521@setu.ie");
insert into players (realname, gamertag, email) values ("Killian", "kio", "c00275417@setu.ie");
insert into players (realname, gamertag, email) values ("Adrian", "MIA", "c0027xxxxx@setu.ie");
